apiVersion: v1
kind: Service
metadata:
  name: iris-api-service
spec:
  selector:
    app: iris-api # Must match the 'app' label in your deployment
  ports:
    - protocol: TCP
      port: 80 # The port clients will connect to on the LoadBalancer (standard HTTP)
      targetPort: 8000 # The port your container is listening on (from your FastAPI app)
  type: LoadBalancer # Creates an external IP address for your service
